### PR TITLE
Use Autoload

### PR DESCRIPTION
**Pull request by plribeiro3000**
Changed `require` usage to `autoload` and moved the files around to reflect its naming.
This PR can't be merged before a necessary change is merge in `fog-core`.

PR on core: fog/fog-core#230

### CODE REVIEW

**Comment by icco** [comment]
Tests are failing because shindont can't find old files

**Comment by plribeiro3000** [comment]
@icco The issue here lies deeper. Check fog/fog-core#256 for a discussion i've started about this if you can.

**Comment by plribeiro3000** [comment]
Cool. @icco The build is fixed now with latest version of `fog-core`. Should i pin its version?

**Comment by plribeiro3000** [comment]
Btw, thanks for all the support on those fixes @geemus !

**Comment by geemus** [comment]
@plribeiro3000 Thanks!

**Comment by geemus** [comment]
Released in 0.0.2

**Pull request merged**
